version: "3.7"
services:
  httpd:
    container_name: httpd
    image: httpd:development
    build:
      context: ./docker/httpd
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
